# openAI：Centralized configuration:
# llm:
#  api_type: "openai"  # or "local"
#  openai_model: "gpt-4-turbo"
#  temperature: 0.3
#kb:
#  correct_kb_path: "./knowledge_bases/correct_kb"
#  embedding_model: "text-embedding-ada-002"
#


# deepseek:

deepseek:
  api_key: "your_deepseek_api_key"
  model: "deepseek-chat"
  temperature: 0.0

agents:
  primary_care:
    system_prompt: "You are a primary care physician with broad general medical knowledge..."
  lead_physician:
    system_prompt: "You are the lead physician overseeing complex cases..."
  specialist_obgyn:
    system_prompt: "You are an OB/GYN specialist with deep expertise..."
  safety_ethics:
    system_prompt: "You are a medical ethics and safety officer..."
  cot_reviewer:
    system_prompt: "You review medical reasoning chains for logical consistency..."

knowledge_bases:
  correct_kb:
    path: "./knowledge_bases/correct_kb"
    embedding_model: "sentence-transformers/all-mpnet-base-v2"
  chain_kb:
    path: "./knowledge_bases/chain_kb"
    embedding_model: "sentence-transformers/all-mpnet-base-v2"

evaluation:
  metrics: ["accuracy", "f1"]
  test_datasets:
    medqa: "./data/medqa"
    pubmedqa: "./data/pubmedqa"